[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyxcoder"
version = "0.0.1"
dependencies = [
    'importlib-metadata; python_version<"3.8"',
    'crcmod'
]

[tool.setuptools]
packages = ["python"]