/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dual_trigger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0abd9ea21c355afe19d2e4791ceaba34)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/droneid/dual_trigger.h>
// pydoc.h is automatically generated in the build directory
#include <dual_trigger_pydoc.h>

void bind_dual_trigger(py::module& m)
{

    using dual_trigger    = ::gr::droneid::dual_trigger;


    py::class_<dual_trigger, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<dual_trigger>>(m, "dual_trigger", D(dual_trigger))

        .def(py::init(&dual_trigger::make),
           py::arg("threshold"),
           py::arg("chunk_size"),
           D(dual_trigger,make)
        )
        




        
        .def("set_threshold",&dual_trigger::set_threshold,       
            py::arg("arg0"),
            D(dual_trigger,set_threshold)
        )

        ;




}








