/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(save_msg.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(44b146565877fccd174ffbf5db839fbc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/droneid/save_msg.h>
// pydoc.h is automatically generated in the build directory
#include <save_msg_pydoc.h>

void bind_save_msg(py::module& m)
{

    using save_msg    = ::gr::droneid::save_msg;


    py::class_<save_msg, gr::block, gr::basic_block,
        std::shared_ptr<save_msg>>(m, "save_msg", D(save_msg))

        .def(py::init(&save_msg::make),
           py::arg("filename"),
           D(save_msg,make)
        )
        




        
        .def("set_filename",&save_msg::set_filename,       
            py::arg("arg0"),
            D(save_msg,set_filename)
        )

        ;




}








