/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(single_trigger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3a70553027cf3b2f02a1a06fb7bcf6f3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/droneid/single_trigger.h>
// pydoc.h is automatically generated in the build directory
#include <single_trigger_pydoc.h>

void bind_single_trigger(py::module& m)
{

    using single_trigger    = ::gr::droneid::single_trigger;


    py::class_<single_trigger, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<single_trigger>>(m, "single_trigger", D(single_trigger))

        .def(py::init(&single_trigger::make),
           py::arg("fc"),
           py::arg("threshold"),
           py::arg("chunk_size"),
           D(single_trigger,make)
        )
        




        
        .def("set_threshold",&single_trigger::set_threshold,       
            py::arg("arg0"),
            D(single_trigger,set_threshold)
        )


        
        .def("set_fc",&single_trigger::set_fc,       
            py::arg("arg0"),
            D(single_trigger,set_fc)
        )

        ;




}








