/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(trig_save.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c6b402f1f07254fa7f4cce4239e45c68)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/droneid/trig_save.h>
// pydoc.h is automatically generated in the build directory
#include <trig_save_pydoc.h>

void bind_trig_save(py::module& m)
{

    using trig_save    = ::gr::droneid::trig_save;


    py::class_<trig_save, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<trig_save>>(m, "trig_save", D(trig_save))

        .def(py::init(&trig_save::make),
           py::arg("chunk_size"),
           py::arg("threshold"),
           py::arg("filename"),
           D(trig_save,make)
        )
        




        
        .def("set_threshold",&trig_save::set_threshold,       
            py::arg("arg0"),
            D(trig_save,set_threshold)
        )

        ;




}








